<?xml version="1.0"?>
<robot name="rc_car" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Basic dimensions -->
  <xacro:property name="chassis_length" value="0.46"/>
  <xacro:property name="chassis_width" value="0.28"/>
  <xacro:property name="chassis_height" value="0.10"/>
  <xacro:property name="wheel_radius" value="0.06"/>
  <xacro:property name="wheel_thickness" value="0.03"/>

  <!-- Placement helpers -->
  <xacro:property name="wheel_base_x" value="${chassis_length / 2.0 - 0.07}"/>
  <xacro:property name="wheel_track_y" value="${chassis_width / 2.0 + wheel_thickness / 2.0 - 0.01}"/>
  <xacro:property name="axle_height" value="${wheel_radius}"/>

  <!-- Mass and inertia approximations -->
  <xacro:property name="chassis_mass" value="3.0"/>
  <xacro:property name="wheel_mass" value="0.25"/>
  <xacro:property name="steer_mass" value="0.05"/>

  <xacro:property name="chassis_ixx" value="${chassis_mass / 12.0 * (chassis_height*chassis_height + chassis_width*chassis_width)}"/>
  <xacro:property name="chassis_iyy" value="${chassis_mass / 12.0 * (chassis_length*chassis_length + chassis_height*chassis_height)}"/>
  <xacro:property name="chassis_izz" value="${chassis_mass / 12.0 * (chassis_length*chassis_length + chassis_width*chassis_width)}"/>

  <xacro:property name="wheel_ixx" value="${wheel_mass / 12.0 * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}"/>
  <xacro:property name="wheel_iyy" value="${wheel_ixx}"/>
  <xacro:property name="wheel_izz" value="${0.5 * wheel_mass * wheel_radius * wheel_radius}"/>

  <!-- Materials -->
  <material name="chassis_grey">
    <color rgba="0.27 0.27 0.3 1.0"/>
  </material>
  <material name="wheel_black">
    <color rgba="0.05 0.05 0.05 1.0"/>
  </material>

  <xacro:macro name="wheel" params="name parent xyz">
    <link name="${name}">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia ixx="${wheel_ixx}" ixy="0.0" ixz="0.0" iyy="${wheel_iyy}" iyz="0.0" izz="${wheel_izz}"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 1.5708 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
        <material name="wheel_black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 1.5708 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
      </collision>
    </link>
    <joint name="${name}_joint" type="continuous">
      <parent link="${parent}"/>
      <child link="${name}"/>
      <origin xyz="${xyz}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
    <gazebo reference="${name}">
      <mu1>1.2</mu1>
      <mu2>1.2</mu2>
      <kp>80000.0</kp>
      <kd>20.0</kd>
    </gazebo>
  </xacro:macro>

  <xacro:macro name="steered_wheel" params="name parent xyz">
    <link name="${name}_steer">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${steer_mass}"/>
        <inertia ixx="0.0002" ixy="0.0" ixz="0.0" iyy="0.0002" iyz="0.0" izz="0.0002"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.01" length="0.04"/>
        </geometry>
        <material name="chassis_grey"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.01" length="0.04"/>
        </geometry>
      </collision>
    </link>
    <joint name="${name}_steer_joint" type="revolute">
      <parent link="${parent}"/>
      <child link="${name}_steer"/>
      <origin xyz="${xyz}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit lower="-0.6" upper="0.6" effort="10.0" velocity="1.5"/>
    </joint>
    <xacro:wheel name="${name}" parent="${name}_steer" xyz="0 0 0"/>
  </xacro:macro>

  <link name="base_link">
    <inertial>
      <origin xyz="0 0 ${chassis_height / 2.0}" rpy="0 0 0"/>
      <mass value="${chassis_mass}"/>
      <inertia ixx="${chassis_ixx}" ixy="0.0" ixz="0.0" iyy="${chassis_iyy}" iyz="0.0" izz="${chassis_izz}"/>
    </inertial>
    <visual>
      <origin xyz="0 0 ${chassis_height / 2.0}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="chassis_grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${chassis_height / 2.0}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
  </link>

  <xacro:steered_wheel name="front_left_wheel" parent="base_link" xyz="${wheel_base_x} ${wheel_track_y} ${axle_height}"/>
  <xacro:steered_wheel name="front_right_wheel" parent="base_link" xyz="${wheel_base_x} ${-wheel_track_y} ${axle_height}"/>
  <xacro:wheel name="rear_left_wheel" parent="base_link" xyz="${-wheel_base_x} ${wheel_track_y} ${axle_height}"/>
  <xacro:wheel name="rear_right_wheel" parent="base_link" xyz="${-wheel_base_x} ${-wheel_track_y} ${axle_height}"/>

  <gazebo reference="base_link">
    <material>Gazebo/Grey</material>
    <mu1>1.2</mu1>
    <mu2>1.2</mu2>
    <kp>80000.0</kp>
    <kd>20.0</kd>
  </gazebo>
</robot>
